apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUUrRENDQTJDZ0F3SUJBZ0lSQUtTd21McWlwdytDbzA2NGNTelVIbkV3RFFZSktvWklodmNOQVFFTEJRQXcKZ1pNeEhqQWNCZ05WQkFvVEZXMXJZMlZ5ZENCa1pYWmxiRzl3YldWdWRDQkRRVEUwTURJR0ExVUVDd3dyY0dGcwpZV1J0UUdOemN5MU5ZV05DYjI5ckxWQnlieTVzYjJOaGJDQW9VR0ZzWkdrZ1FtRnNZWHB6S1RFN01Ea0dBMVVFCkF3d3liV3RqWlhKMElIQmhiR0ZrYlVCamMzTXRUV0ZqUW05dmF5MVFjbTh1Ykc5allXd2dLRkJoYkdScElFSmgKYkdGNmN5a3dIaGNOTWpJd09URTJNVE0wTkRNeVdoY05Nekl3T1RFMk1UTTBORE15V2pDQmt6RWVNQndHQTFVRQpDaE1WYld0alpYSjBJR1JsZG1Wc2IzQnRaVzUwSUVOQk1UUXdNZ1lEVlFRTERDdHdZV3hoWkcxQVkzTnpMVTFoClkwSnZiMnN0VUhKdkxteHZZMkZzSUNoUVlXeGthU0JDWVd4aGVuTXBNVHN3T1FZRFZRUUREREp0YTJObGNuUWcKY0dGc1lXUnRRR056Y3kxTllXTkNiMjlyTFZCeWJ5NXNiMk5oYkNBb1VHRnNaR2tnUW1Gc1lYcHpLVENDQWFJdwpEUVlKS29aSWh2Y05BUUVCQlFBRGdnR1BBRENDQVlvQ2dnR0JBS21OVDVjOWhFamtTUU44TEhVT1VtRUpGdU5QCjFFTkl6eDAwYWFaOFJpYlU5SWtvZitJWnFkYTAxUUloQWRxTmc5UnRYYzViZmVveXNMaW9xN2tiYnNicGZTTEIKNGh0LysvYlpRaGN5WEFxS0VWQTk5Tndiai94VzVKMmUwMlFUeXR3cUxaMWhYMHgwbFl6WUxtMUpHbGI2WllFSAorZ2dhSTlmWG1XWDh0bEFINUNsT2pINnZLVi9hWGpBSTVrc3ZucG8xd0xmTUkyQnlMbU8xcUF4WXBQdVp0OFZSCmNMdlZtN3UyN1ZXaGRZZGlMRGIxVG1iRjFGZHpRaWxlK09iVFpDajNHUXI4OWdOZHJ3c1VjejFsT0g3anpUMHkKUmtMU1MyREdYVUtnMXE5UUNqTjRkWWNXZXA2eUplUEhwMlZBOFEyeWUyVEEvS0VtNUJudk5WU0VhMkdBNytNVgo1clo3Y25JcnlNNlFkM2MvMEZsa0doZkZjVW0vRG96TE0ydlV6MGxnSEdZVUZaZ1crTDBFTEE3ZU9YU0tLYThXCnczZ0RGUDIzUkZNUGxMM0hxNmorbmtMdi9jRWxJajY2OHRrS01jZEhwallMZ2l5MTd5Rm1DZXZKWk5jaFNaWEcKZ1czMERLR2JFb3FKSytZeVlrNTVxYUJjeEhmdE1hWTRVUUJiU1FJREFRQUJvMFV3UXpBT0JnTlZIUThCQWY4RQpCQU1DQWdRd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFEQWRCZ05WSFE0RUZnUVV3VTB0a1h4K3puUXRuZjVVCm5CTnJRRitZeFBvd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFHaFJvSTVxYWdBbTVNSjh0Ryt3K0x3cTNpbnQKV3FnbllqR3NmSzd3WjZlTGVFU2FTOStYWVV4bmQvQkdFS1VZY1hFZDNVRlVWSEpLQWZNSUtROElhYzRadXJqOQp1b2dHTlU2c09UR0p1enRBN1lCMUJqbFE2ZGRIWlR2UGw0a0RxcjRwdHN3MldqVnZiYjVnV0RkMWk2TTVvcTN2CjdmNE5ibUQ3ZjBCbXRFUUI0bGhrNkJzbU9PUmdJbnBuUVBRUWhYYml6WGU2RVRMUytJT1BGeFNwUkl0MEtJcFMKU01Wem43V2pDN281MkJyUnp0RFdvdnBHYld2T3Zpem1oeHhUbTl5Wkc4RnR6NWNUcUJJa0gvUGlsQWk5Y3IvcQpZZCt5U2g5cGNpdkpwdlhVUHdvNWhFcFZlY2h2d0c0MElpVXd2K1lhMHJ4ZVNXS3B2NTRrU09mem9KaS9iWUpOCjMzeGRBdlVJM0tsU3ZXSmFiNzdoZUxkQytsK3k4dVFlNngrL1ZxaFZNTDlJcFQ5RGNsbER6NFFNa2t2SitmT3EKZTRoamVKYk5HMUEzM1J3S0o5L1Y2RmdUVlI3YXhZY2N6SnZGeVpycGt2WmxGdCt6cURES01hYytIdTBhY1FxdgpwQWk2UE1KOFEyR24wSzA2TXExeUJmSCtFYStNZGszZ2JrTWRpdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUcvd0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQnVrd2dnYmxBZ0VBQW9JQmdRQ3BqVStYUFlSSTVFa0QKZkN4MURsSmhDUmJqVDlSRFNNOGROR21tZkVZbTFQU0pLSC9pR2FuV3ROVUNJUUhhallQVWJWM09XMzNxTXJDNApxS3U1RzI3RzZYMGl3ZUliZi92MjJVSVhNbHdLaWhGUVBmVGNHNC84VnVTZG50TmtFOHJjS2kyZFlWOU1kSldNCjJDNXRTUnBXK21XQkIvb0lHaVBYMTVsbC9MWlFCK1FwVG94K3J5bGYybDR3Q09aTEw1NmFOY0MzekNOZ2NpNWoKdGFnTVdLVDdtYmZGVVhDNzFadTd0dTFWb1hXSFlpdzI5VTVteGRSWGMwSXBYdmptMDJRbzl4a0svUFlEWGE4TApGSE05WlRoKzQ4MDlNa1pDMGt0Z3hsMUNvTmF2VUFvemVIV0hGbnFlc2lYang2ZGxRUEVOc250a3dQeWhKdVFaCjd6VlVoR3RoZ08vakZlYTJlM0p5SzhqT2tIZDNQOUJaWkJvWHhYRkp2dzZNeXpOcjFNOUpZQnhtRkJXWUZ2aTkKQkN3TzNqbDBpaW12RnNONEF4VDl0MFJURDVTOXg2dW8vcDVDNy8zQkpTSSt1dkxaQ2pISFI2WTJDNElzdGU4aApaZ25yeVdUWElVbVZ4b0Z0OUF5aG14S0tpU3ZtTW1KT2VhbWdYTVIzN1RHbU9GRUFXMGtDQXdFQUFRS0NBWUVBCnFYRFU5MW04MTNOOEhBVitFRVVOd25kbzdpV2JCTnJBVUhsT2s5aGg2dkNxcUY5VzNjZXoyU1BDTTJ4MUE4cWsKMGlleHRVWHRvWnlpeXdlVkJWb0s3TEh1SWt3TUFGdDRuQW9tYURRbGswckRYcU5zRG9OazgxS0xDWkh0dzNlYwpKVVhwYS93aFZyQ3p1NXRYV2xQU0JOWWJsa1U0Yzl4YnNacCtiRk9PaHBBOFRhTjMrQ3BvZUtncnRHbFFiQmJjCnMxUEFrbTFwZFRybWJUTGZDK2VTaVBYbmwwTjZHOXl1MDN0TjEyT1Jwb2hQazJTMnd6STBzR2c0MkV0WEJxWjkKTTI0dGVJOGZGaHgzUGIvWE1qVVRUbzVBbmlVS2ExaEVabFgyR3Z3UHNDQWNoeE9TSHdyaVQ0Q2VBYTJmQjh4TQo0SXhvWlpjd3FXOXliL2lySUgrZGpaSFA4TlVSb1pYY0Y4TytpUmxuWi9CVEJMUkRNWVp2b1V3T2c1WmkwNVdICk5rSS9HMkdtcGFFMVpXM3E4Sm5yekhIdDdvOC8yTVd2VHFHc1pxNU9Md0tnS2VnbEg5c3paYmx4MGJOU1ppL1oKNml2b2k3R3FscDZkd2NzMFJmZ1RudUtkN0Urb0cxRUJPVkQyRXZlUkZuZG4wbnZadFM5ck5OR2FhSjM1bUlkaApBb0hCQU5ic0RnVHltS0NNM2ExdlMrR2NVbEhMQU5WQVlOSjFaVFU2TmxSTTE3YXpLU1pqVXFqVUJaMVVVY2ZKCjB2a1lzSE9hdGhKZVVSUjR5YnJKTXpOV0tuUE01VUxQSUwyT0NVaW4zaU9YK1ZWUEQxbHZZbXNtR1ZZU2N3aEUKd1RtYitkRjVDaTBXVzJjTTFiY2pPK0VkMU5tTklYOW9KVE5teUFSZEpVYmx6MVd2eHNaUlRrU3BoMmc2WGxLcgp4UlVOWkNnOUdDM3FabXBnSndwQmI1Szh2cGF0b0JXeW14dmxmUDcrWUFCM3p6NURpcWhyc01iRTRhWWVaVDYrCkNkb0xQUUtCd1FESjlWYVBzbHROUGJuaGs3ZU5aTVE3NWFyWUNxRHV2UEl1NmxmeGJGWkt3STVBVDNFOGdPbm0KS0cvWFB1eGtxN0Y5dzlhYk9RaDNUSHg3MDV1RExaYkVtZTdWRW16cnFiNWgzMU5kVGMrZjk3TXVxUmxlM1BUbgpzUFJyZDI5Ung2Z2FyRkUzc3NIZEJIOFNWNnRKN2llMm9kYlpHVHRhWEZabWxRK3ZTZFBOSTZta2JNcGdXanBXCkpYZ0NkYlo4Nk9SQXUwSk9HbUJmVGxSOXhIcUNweUFCZHhkQkovOHpLbUdvdjRUY3BVVGQvemdMK3dXTXBDSncKQWZHUldzUEVRUDBDZ2NCUGhOZExEVmRiVDhOVlFEQ2JNUE5rUCsvMjl2TGI2NE9leGdNRC9jcHlWcWVMQklTNAo0bm1SVkhsTnFtYmNzejNXQ0JBRmk5QUQrd3pvaHpqaWJhY1hZV0FSOEFEMUlYQmQ2WDVQUFJPTGRNMEJFaTBmCjUrREg3OXVQMjZDQ2FDdHVUWkp1VEM5VldYSlphRGZuZXRvZUJCRzR5aGU1aFBYTVo0bzdTUndGWUJ2emxIR1oKQmdDTGw4eitXWDk1NHBLRU1OYVpabml1TXhVK3ZpZEI2NE80ekZUR3NtYWhVNitEeVNwTUFnZ3p5Vm1zSnV3cApIdjgrTDFEV2ZnbTNHeUVDZ2NFQXRVY2N2YnN3clBKOUNQZ1l5RGZzMUg3Z2pTOXRLUjQ4bk5RSXdGR29XMHpmCjR1WHNGSXo2Wm5kaGZHbWtzdkJTVHpzY1JSUTZmeXNPaWU5MUpaZ2tQckNWYW5neGdJOUtybnRSVHV6ck13R1oKdW9aYW1ZWG41cGcxck1qMkNRZ1g0bWxPTlpxazNRaU9MeDYyUjVRWDNaMERScmVaU1JDZEZWTXpVdm9IdlprSApTdW5EOWh6SFJGQTVtcXVpZEJodjJaSzhmM0s1a3BLeTBIa3VKbHh4SkIrTHBoYUt3WmlITkh0RWZQRjBFWGhuCkRJbnpmenhORlJFSmpwbFVJN0xaQW9IQkFKdGZnOXhyZ1VXaVUyWTZkd0lOQ2ZEY080VDc2QlJlaDJCWkIwMVcKZVprbFpCS0wrcE1lRFFDV1ZSWHJkT1VaQ0IxVjhkT0NrWUlSNHZDVjhLZXhkeDkxRG5RbGU2eXNPUVJuUVRFYgo2ckZ6ZE05d1Ezdk9zbXA5TkpKa1hiT3ZZMnNCUlVobnZYcHgzM001T3NQaXl2NHBtZXhSekMzRWppNDN6T3RzCjdDUTl0OUJNcm55SmJ3a1FsbGFzZFd6QURCVUhqVW8rekFkMXRCZGZDR0l6M2RDaWc0cWpFNmJ0b01WVUpLUEQKbjhndldHcTBSVjlVMG4zN3RXcXRKREhKakE9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: ca-key-pair
  namespace: ingress-system
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  namespace: ingress-system
spec:
  ca:
    secretName: ca-key-pair
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: setup-script
  namespace: ingress-system
data:
  setup.sh: |
    echo "$TRUSTED_CERT" > /usr/local/share/ca-certificates/ca.crt && update-ca-certificates
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-custom-setup
  namespace: ingress-system
  labels:
    k8s-app: node-custom-setup
spec:
  selector:
    matchLabels:
      k8s-app: node-custom-setup
  template:
    metadata:
      labels:
        k8s-app: node-custom-setup
    spec:
      hostPID: true
      hostNetwork: true
      initContainers:
      - name: init-node
        command: ["nsenter"]
        args: ["--mount=/proc/1/ns/mnt", "--", "sh", "-c", "$(SETUP_SCRIPT)"]
        image: debian
        env:
        - name: TRUSTED_CERT
          valueFrom:
            secretKeyRef:
              name: ca-key-pair
              key: tls.crt
        - name: SETUP_SCRIPT
          valueFrom:
            configMapKeyRef:
              name: setup-script
              key: setup.sh
        securityContext:
          privileged: true
      containers:
      - name: wait
        image: k8s.gcr.io/pause:3.1
