apiVersion: v1
kind: Namespace
metadata:
  name: container-registry
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: docker-registry-ui
  namespace: container-registry
spec:
  repo: "https://helm.joxit.dev"
  chart: docker-registry-ui
  targetNamespace: container-registry
  valuesContent: |-
    registry:
      enabled: true
      image: "registry:2"
      ingress:
        enabled: true
        host: registry.rancher-decktop.intra
        ingressClassName: ""
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
          nginx.ingress.kubernetes.io/proxy-body-size: 200m
        tls:
        - secretName: tls-docker-registry-cert
          hosts:
          - registry.rancher-decktop.intra
    ui:
      deleteImages: true
      proxy: true
      dockerRegistryUrl: "http://docker-registry-ui-docker-registry-ui-registry-server:5000"
      ingress:
        enabled: true
        ingressClassName: ""
        host: docker.rancher-decktop.intra
        annotations:
          cert-manager.io/cluster-issuer: ca-issuer
        tls:
        - secretName: tls-docker-registry-ui-cert
          hosts:
          - docker.rancher-decktop.intra
