apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
    import /etc/coredns/custom/*.server
  NodeHosts: |
    192.168.9.91 lima-rancher-desktop
    192.168.9.91 registry.rancher-decktop.intra
    192.168.9.91 defectdojo.rancher-decktop.intra
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
